[[rule]]
files = "*"
all = [
    "marko.spasic@oracle.com",
    "peter.hofer@oracle.com",
    "bernhard.urban-forster@oracle.com",
]
any = [
    "marko.spasic@oracle.com",
    "peter.hofer@oracle.com",
    "bernhard.urban-forster@oracle.com",
]
